[package]
name = "bitcoin-seed-tool"
version = "0.1.0"
authors = ["William Casarin <jb55@jb55.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-bip39 = "0.7.0"
bitcoin_hashes = "0.7.4"
